//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRandomNumberGeneratorService", Namespace="http://tempuri.org/")]
    public partial class RandomNumberGeneratorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRandomNumbersDateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RandomNumberGeneratorService() {
            this.Url = global::ConsoleApp1.Properties.Settings.Default.ConsoleApp1_localhost_RandomNumberGeneratorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRandomNumbersDateCompletedEventHandler GetRandomNumbersDateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRandomNumberGeneratorService/GetRandomNumbersDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RandomNumberService.Models")]
        public NumberDateModel[] GetRandomNumbersDate() {
            object[] results = this.Invoke("GetRandomNumbersDate", new object[0]);
            return ((NumberDateModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRandomNumbersDateAsync() {
            this.GetRandomNumbersDateAsync(null);
        }
        
        /// <remarks/>
        public void GetRandomNumbersDateAsync(object userState) {
            if ((this.GetRandomNumbersDateOperationCompleted == null)) {
                this.GetRandomNumbersDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandomNumbersDateOperationCompleted);
            }
            this.InvokeAsync("GetRandomNumbersDate", new object[0], this.GetRandomNumbersDateOperationCompleted, userState);
        }
        
        private void OnGetRandomNumbersDateOperationCompleted(object arg) {
            if ((this.GetRandomNumbersDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandomNumbersDateCompleted(this, new GetRandomNumbersDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RandomNumberService.Models")]
    public partial class NumberDateModel {
        
        private System.DateTime numberDateField;
        
        private bool numberDateFieldSpecified;
        
        private int randomNumberField;
        
        private bool randomNumberFieldSpecified;
        
        /// <remarks/>
        public System.DateTime NumberDate {
            get {
                return this.numberDateField;
            }
            set {
                this.numberDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberDateSpecified {
            get {
                return this.numberDateFieldSpecified;
            }
            set {
                this.numberDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int RandomNumber {
            get {
                return this.randomNumberField;
            }
            set {
                this.randomNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RandomNumberSpecified {
            get {
                return this.randomNumberFieldSpecified;
            }
            set {
                this.randomNumberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRandomNumbersDateCompletedEventHandler(object sender, GetRandomNumbersDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandomNumbersDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandomNumbersDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NumberDateModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NumberDateModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591